#!/bin/bash

cd build

#NB: never building API doc with integration
if [ "$PACKAGE_HAS_TESTS" = true ] ; then
      cmake -DREQUIRED_PACKAGES_AUTOMATIC_DOWNLOAD=ON -DADDITIONNAL_DEBUG_INFO=OFF -DBUILD_AND_RUN_TESTS=ON -DBUILD_TESTS_IN_DEBUG=ON -DBUILD_COVERAGE_REPORT=ON -DENABLE_PARALLEL_BUILD=ON -DBUILD_EXAMPLES=OFF -DBUILD_API_DOC=ON -DGENERATE_INSTALLER=ON -DWORKSPACE_DIR="../binaries/pid-workspace" ..
else
       cmake -DREQUIRED_PACKAGES_AUTOMATIC_DOWNLOAD=ON -DBUILD_AND_RUN_TESTS=OFF -DENABLE_PARALLEL_BUILD=ON -DBUILD_EXAMPLES=OFF -DBUILD_API_DOC=ON -DBUILD_TESTS_IN_DEBUG=OFF -DBUILD_COVERAGE_REPORT=OFF -DADDITIONNAL_DEBUG_INFO=OFF -DGENERATE_INSTALLER=ON -DWORKSPACE_DIR="../binaries/pid-workspace" ..
fi

# always generating the dependecies file of the package
cmake --build . --target list_dependencies -- write_file=true

cd ..
