#!/bin/bash

cd build

#NB: never building API doc with integration
if [ "$PACKAGE_HAS_TESTS" = true ] ; then
   if [ "$PACKAGE_HAS_EXAMPLES" = true ] ; then
       cmake -DREQUIRED_PACKAGES_AUTOMATIC_DOWNLOAD=ON -DADDITIONNAL_DEBUG_INFO=ON -DBUILD_AND_RUN_TESTS=ON -DBUILD_TESTS_IN_DEBUG=ON -DBUILD_COVERAGE_REPORT=ON -DENABLE_PARALLEL_BUILD=ON -DBUILD_EXAMPLES=ON -DBUILD_API_DOC=OFF -DBUILD_STATIC_CODE_CHECKING_REPORT=ON -DWORKSPACE_DIR="../binaries/pid-workspace" ..
   else
      cmake -DREQUIRED_PACKAGES_AUTOMATIC_DOWNLOAD=ON -DADDITIONNAL_DEBUG_INFO=ON -DBUILD_AND_RUN_TESTS=ON -DBUILD_TESTS_IN_DEBUG=ON -DBUILD_COVERAGE_REPORT=ON -DENABLE_PARALLEL_BUILD=ON -DBUILD_EXAMPLES=OFF -DBUILD_API_DOC=OFF -DBUILD_STATIC_CODE_CHECKING_REPORT=ON -DWORKSPACE_DIR="../binaries/pid-workspace" ..
   fi
else
    if [ "$PACKAGE_HAS_EXAMPLES" = true ] ; then
       cmake -DREQUIRED_PACKAGES_AUTOMATIC_DOWNLOAD=ON -DBUILD_AND_RUN_TESTS=OFF -DENABLE_PARALLEL_BUILD=ON -DBUILD_EXAMPLES=ON -DBUILD_API_DOC=OFF -DBUILD_STATIC_CODE_CHECKING_REPORT=ON -DADDITIONNAL_DEBUG_INFO=ON -DWORKSPACE_DIR="../binaries/pid-workspace" ..
    else
       cmake -DREQUIRED_PACKAGES_AUTOMATIC_DOWNLOAD=ON -DBUILD_AND_RUN_TESTS=OFF -DENABLE_PARALLEL_BUILD=ON -DBUILD_EXAMPLES=OFF -DBUILD_API_DOC=OFF -DBUILD_STATIC_CODE_CHECKING_REPORT=ON -DADDITIONNAL_DEBUG_INFO=ON -DWORKSPACE_DIR="../binaries/pid-workspace" ..
    fi
fi

# always generating the dependencies file of the package
cmake --build . --target list_dependencies -- write_file=true

cd ..
