/*      File: velocity_proxy.h
 *       This file is part of the program open-phri
 *       Program description : OpenPHRI: a generic framework to easily and
 * safely control robots in interactions with humans Copyright (C) 2017 -
 * Benjamin Navarro (LIRMM). All Right reserved.
 *
 *       This software is free software: you can redistribute it and/or modify
 *       it under the terms of the LGPL license as published by
 *       the Free Software Foundation, either version 3
 *       of the License, or (at your option) any later version.
 *       This software is distributed in the hope that it will be useful,
 *       but WITHOUT ANY WARRANTY without even the implied warranty of
 *       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *       LGPL License for more details.
 *
 *       You should have received a copy of the GNU Lesser General Public
 * License version 3 and the General Public License version 3 along with this
 * program. If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * @file velocity_proxy.h
 * @author Benjamin Navarro
 * @brief Definition of the VelocityProxy class
 * @date April 2017
 * @ingroup OpenPHRI
 */

#pragma once

#include <OpenPHRI/velocity_generators/velocity_generator.h>
#include <OpenPHRI/definitions.h>
#include <functional>

namespace phri {

/** @brief Generates a velocity based on an externally managed one.
 *  @details Can be useful to add a velocity generated by an external library.
 */
class VelocityProxy : public VelocityGenerator {
public:
    /** @brief Construct a velocity proxy given an externally managed velocity
     *  @param frame The reference frame in which the velocity is expressed
     */
    explicit VelocityProxy(TwistConstPtr velocity,
                           ReferenceFrame frame = ReferenceFrame::TCP);

    explicit VelocityProxy(TwistConstPtr velocity, ReferenceFrame frame,
                           const std::function<void(void)>& update_func);

    virtual ~VelocityProxy() = default;

protected:
    virtual void update(Twist& velocity) override;

    TwistConstPtr external_velocity_;
    std::function<void(void)> update_func_;
};

using VelocityProxyPtr = std::shared_ptr<VelocityProxy>;
using VelocityProxyConstPtr = std::shared_ptr<const VelocityProxy>;

} // namespace phri
