/*
 *  Copyright (C) 2017 Benjamin Navarro <contact@bnavarro.info>
 *
 *  This file is part of RSCL <https://gite.lirmm.fr/navarro/RSCL>.
 *
 *  RSCL is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  RSCL is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with RSCL.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * @file external_force.h
 * @author Benjamin Navarro
 * @brief Definition of the ExternalForce class
 * @date June 2017
 * @ingroup RSCL
 */

#pragma once

#include <RSCL/force_generators/force_generator.h>
#include <RSCL/robot.h>
#include <RSCL/definitions.h>

namespace RSCL {

/** @brief Generates a force based on an externally managed one.
 *  @details Can be useful to add a velocity generated by an external library or a force sensor.
 */
class ExternalForce : public ForceGenerator {
public:
	/** @brief Construct an external fworce generator based on a given robot
	 */
	ExternalForce(RobotConstPtr robot);
	~ExternalForce() = default;

	virtual Vector6d compute() override;

private:
	Vector6dConstPtr external_force_;
};

using ExternalForcePtr = std::shared_ptr<ExternalForce>;
using ExternalForceConstPtr = std::shared_ptr<const ExternalForce>;

} // namespace RSCL
