/*
 *  Copyright (C) 2017 Benjamin Navarro <contact@bnavarro.info>
 *
 *  This file is part of RSCL <https://gite.lirmm.fr/navarro/RSCL>.
 *
 *  RSCL is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  RSCL is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with RSCL.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * @file force_proxy.h
 * @author Benjamin Navarro
 * @brief Definition of the ForceProxy class
 * @date April 2017
 * @ingroup RSCL
 */

#pragma once

#include <RSCL/force_generators/force_generator.h>
#include <RSCL/definitions.h>

namespace RSCL {

/** @brief Generates a force based on an externally managed one.
 *  @details Can be useful to add a velocity generated by an external library or a force sensor.
 */
class ForceProxy : public ForceGenerator {
public:
	/** @brief Construct a force proxy given an externally managed force
	 *  @param frame The reference frame in which the force is expressed
	 */
	ForceProxy(Vector6dConstPtr force, ReferenceFrame frame = ReferenceFrame::TCP);
	~ForceProxy() = default;

	virtual Vector6d compute() override;

private:
	Vector6dConstPtr force_;
};

using ForceProxyPtr = std::shared_ptr<ForceProxy>;
using ForceProxyConstPtr = std::shared_ptr<const ForceProxy>;

} // namespace RSCL
