/*
 *  Copyright (C) 2017 Benjamin Navarro <contact@bnavarro.info>
 *
 *  This file is part of OpenPHRI <https://gite.lirmm.fr/navarro/OpenPHRI>.
 *
 *  OpenPHRI is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  OpenPHRI is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with OpenPHRI.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * @file joint_velocity_proxy.h
 * @author Benjamin Navarro
 * @brief Definition of the JointVelocityProxy class
 * @date April 2017
 * @ingroup OpenPHRI
 */

#pragma once

#include <OpenPHRI/joint_velocity_generators/joint_velocity_generator.h>
#include <OpenPHRI/definitions.h>

namespace phri {

/** @brief Generates a joint_velocity based on an externally managed one.
 *  @details Can be useful to add a joint_velocity generated by an external library.
 */
class JointVelocityProxy : public JointVelocityGenerator {
public:
	JointVelocityProxy(VectorXdConstPtr joint_velocity);
	~JointVelocityProxy() = default;

	virtual VectorXd compute() override;

private:
	VectorXdConstPtr joint_velocity_;
};

using JointVelocityProxyPtr = std::shared_ptr<JointVelocityProxy>;
using JointVelocityProxyConstPtr = std::shared_ptr<const JointVelocityProxy>;

} // namespace phri
